"""Write the LaTeX parameter-sensitivity table from the sensitivity pipeline's own definitions.

Nothing in the table is typed by hand, so it cannot drift from what the runs actually sample:
  - which parameters, in which order:  ScenarioRun_Parallel._SAMPLED_PARAM_ORDER
  - their bounds, as multipliers:      Sobol.PARAM_MULTIPLIERS (LatHyper's l_bounds/u_bounds)
  - their reference values:            the NewCal<Model><Vintage>_Calibrated.py files LatHyper
                                       samples around, loaded with the same _load_calibration;
                                       alpha_iCB is a run-mode switch, so it is read from
                                       _DEFAULT_CALIB_SWITCHES exactly as generate_sample() does
  - their notation:                    Sobol_Plot.PARAM_TEX, i.e. the Sobol/OT figure labels

A few parameters are recalibrated for each IAM x vintage. By default the table spans all nine
calibrations: those rows show the range of reference values and the union of the nine intervals,
marked with a dagger. --model/--vintage restrict the table to one calibration.

Command line
------------
    python3 Sensitivity_Table.py                                 # all nine calibrations
    python3 Sensitivity_Table.py --model=REMIND --vintage=2022   # one calibration
    python3 Sensitivity_Table.py --out=/path/to/table.tex
"""

import argparse
import math
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
# Importing ScenarioRun_Parallel (via Sobol) moves the working directory to the FASMID root,
# which _load_calibration's relative paths need.
from Sobol import PARAM_MULTIPLIERS, params
from ScenarioRun_Parallel import _DEFAULT_CALIB_SWITCHES, _load_calibration
from Sobol_Plot import PARAM_TEX

_TABLE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Results', 'Tables')
MODELS = ('GCAM', 'MESSAGE', 'REMIND')
VINTAGES = (2020, 2021, 2022)


def reference_values(model, vintage):
    """{parameter: reference value} for one calibration, read the way generate_sample() reads it."""
    ns = {'np': np}
    # The 2020 vintage's calibration files carry no year suffix.
    _load_calibration(ns, model, "" if vintage == 2020 else vintage)
    values = {p: ns[p] for p in params}
    values['alpha_iCB'] = _DEFAULT_CALIB_SWITCHES['alpha_iCB']
    return values


def fmt(x):
    """Number for math mode: up to 10 significant digits, enough to keep the products of the
    multipliers exact (11.05 x 1.025 = 11.32625) while staying clear of float noise; scientific
    notation below 1e-3."""
    s = f"{x:.10g}"
    if 'e' in s:
        mantissa, exponent = s.split('e')
        return f"{mantissa}\\times10^{{{int(exponent)}}}"
    return s


def sort_key(tex):
    """Alphabetical by symbol name, as in the paper's table: \\bar{\\mu} files under mu."""
    return re.sub(r'[\\{}]', '', tex.replace('\\bar{', '')).lower()


def build_rows(calibrations):
    refs = [reference_values(m, v) for m, v in calibrations]
    rows, varying = [], []
    for p in params:
        lo_mult, hi_mult = PARAM_MULTIPLIERS[p]
        half_width = hi_mult - 1
        if not math.isclose(1 - lo_mult, half_width, abs_tol=1e-12):
            raise ValueError(f"{p}: bounds {lo_mult}-{hi_mult} are not symmetric, so they cannot "
                             f"be shown as a single +/- range.")
        vals = [r[p] for r in refs]
        vmin, vmax = min(vals), max(vals)
        if vmin <= 0:
            raise ValueError(f"{p}: non-positive reference value {vmin}; the multiplier bounds "
                             f"would be inverted.")
        if math.isclose(vmin, vmax, rel_tol=1e-12):
            ref_cell = f"${fmt(vmin)}$"
        else:
            ref_cell = f"${fmt(vmin)}$--${fmt(vmax)}^\\dagger$"
            varying.append(p)
        interval = f"$[{fmt(lo_mult * vmin)},\\ {fmt(hi_mult * vmax)}]$"
        tex = PARAM_TEX[p]
        rows.append((sort_key(tex), f"${tex}$ & {ref_cell} & {interval} & "
                                    f"$\\pm {100 * half_width:.1f}\\%$ \\\\"))
    rows.sort()
    return [r for _, r in rows], varying


def render(rows, note):
    return "\n".join([
        "% Generated by FASMID/Sensitivity_Analysis/Sensitivity_Table.py: change the pipeline",
        "% (Sobol.PARAM_MULTIPLIERS, the calibration files, Sobol_Plot.PARAM_TEX) and rerun it.",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\small",
        "\\caption{Parameter Sensitivity Analysis}",
        "\\label{tab:param_sensitivity}\\label{tab:senspar}\\label{tab:sensrange}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Parameter & Reference Value & Sensitivity Interval & Range \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "",
        "\\smallskip",
        "\\begin{minipage}{\\linewidth}\\footnotesize",
        note,
        "\\end{minipage}",
        "\\end{table}",
        "",
    ])


def main():
    parser = argparse.ArgumentParser(description="Write the LaTeX parameter-sensitivity table.")
    parser.add_argument('--model', choices=MODELS, help="restrict to one IAM calibration")
    parser.add_argument('--vintage', type=int, choices=VINTAGES,
                        help="restrict to one NGFS vintage")
    parser.add_argument('--out', help="output .tex path (default: Results/Tables/)")
    args = parser.parse_args()

    models = (args.model,) if args.model else MODELS
    vintages = (args.vintage,) if args.vintage else VINTAGES
    calibrations = [(m, v) for m in models for v in vintages]
    rows, varying = build_rows(calibrations)

    interval_note = ("Sensitivity interval: reference value $\\times\\,(1 \\pm$ range$)$, the box "
                     "sampled by the Latin hypercube calibration search and by the Sobol analysis")
    if len(calibrations) == 1:
        note = f"{interval_note}, around the {models[0]} {vintages[0]} calibration."
    else:
        note = (f"{interval_note}. $^\\dagger$Recalibrated for each IAM and NGFS vintage "
                f"({', '.join(models)}; {', '.join(map(str, vintages))}): the reference value is "
                f"the range over these {len(calibrations)} calibrations and the interval the union "
                f"of their intervals.")

    suffix = "" if len(calibrations) == 9 else "_" + "_".join(
        [*([args.model] if args.model else []), *([str(args.vintage)] if args.vintage else [])])
    out = args.out or os.path.join(_TABLE_DIR, f"param_sensitivity{suffix}.tex")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, 'w') as f:
        f.write(render(rows, note))

    print(f"{len(rows)} parameters over {len(calibrations)} calibration(s) -> {out}")
    if varying:
        print(f"Calibration-specific (dagger): {', '.join(varying)}")


if __name__ == "__main__":
    main()
